export const cardsArray = [
    `<img src="img/cards/туз пики.png">`,
    `<img src="img/cards/король пики.png">`,
    `<img src="img/cards/дама пики.png">`,
    `<img src="img/cards/валет пики.png">`,
    `<img src="img/cards/10 пики.png">`,
    `<img src="img/cards/9 пики.png">`,
    `<img src="img/cards/8 пики.png">`,
    `<img src="img/cards/7 пики.png">`,
    `<img src="img/cards/6 пики.png">`,

    `<img src="img/cards/туз черви.png">`,
    `<img src="img/cards/король черви.png">`,
    `<img src="img/cards/дама черви.png">`,
    `<img src="img/cards/валет черви.png">`,
    `<img src="img/cards/10 черви.png">`,
    `<img src="img/cards/9 черви.png">`,
    `<img src="img/cards/8 черви.png">`,
    `<img src="img/cards/7 черви.png">`,
    `<img src="img/cards/6 черви.png">`,

    `<img src="img/cards/туз бубны.png">`,
    `<img src="img/cards/король бубны.png">`,
    `<img src="img/cards/дама бубны.png">`,
    `<img src="img/cards/валет бубны.png">`,
    `<img src="img/cards/10 бубны.png">`,
    `<img src="img/cards/9 бубны.png">`,
    `<img src="img/cards/8 бубны.png">`,
    `<img src="img/cards/7 бубны.png">`,
    `<img src="img/cards/6 бубны.png">`,

    `<img src="img/cards/туз крести.png">`,
    `<img src="img/cards/король крести.png">`,
    `<img src="img/cards/дама крести.png">`,
    `<img src="img/cards/валет крести.png">`,
    `<img src="img/cards/10 крести.png">`,
    `<img src="img/cards/9 крести.png">`,
    `<img src="img/cards/8 крести.png">`,
    `<img src="img/cards/7 крести.png">`,
    `<img src="img/cards/6 крести.png">`,
];
